### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by dobri12352** [Hembi/cs16-pterodactyl-egg#1]
how to make to can join all craked cs 1.6 help pls

**Comment by Hembi** [comment]
If you installed this egg, you can install Metamod and Metamod plugins to your server. It is not recommended to crack your server, but if you would like to allow connect non-steam players to your server you have to install dproto metamod plugin, or if you install ReHLDS, then you have to install Reunion metamod plugin.

**Comment by NishiVT** [comment]
/entrypoint.sh: line 25: ./hlds_run: No such file or directory
