### ISSUE TITLE
Probléma a server browser-nál.

### ISSUE THREAD

**Issue by ilovetdi** [Hembi/cs16-pterodactyl-egg#10]
Hali ! 

A szerver feltelepül könnyedén, el is indul de a SB-ben nem jelenik meg.
Megadtam neki a szükséges portokat is 27015,stb

"[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from pterodactyl/core 
Status: Image is up to date for quay.io/pterodactyl/core:source 
Digest: sha256:3265256f9d729a38cd73f64b2e0545699848a378bee0b15f7c7c6469f07a4d10 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ ./hlds_run -pidfile hlds_27015 -game cstrike -secure +port 27015 +sv_lan 0 +maxplayers 32 +map de_dust2 +sys_ticrate 1200 -pingboost 2 -norestart
Console initialized.
Using breakpad crash handler
Setting breakpad minidump AppID = 10
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 19:52:19 Aug  3 2020 (8684)
STEAM Auth Server
Server IP address 172.19.0.2:27015
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
CAppInfoCacheReadFromDiskThread took 4 milliseconds to initialize
dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
couldn't exec listip.cfg
couldn't exec banned.cfg
Connection to Steam servers successful.
container@pterodactyl~ Server marked as running...
   VAC secure mode is activated.

"

Valami tipp ?
Köszi

**Comment by Hembi** [comment]
https://gaming.stackexchange.com/questions/306509/how-can-i-show-my-counter-strike-server-in-the-find-servers-list

sv_lan 0
sv_region 255
De elvileg ezek a default értékek, a region-ban nem vagyok biztos, a server.cfg-be írd be és indítsd újra a szervert.

Lehet, hogy kell várni egy napot, úgy, hogy aktívan fut folyamatosan, mire bekerül a listába.

Ezen az API-n tudod tesztelni, hogy bekerült-e a rendszerükbe, ha kicseréled az IP címet a tiedre (IP_ADDRESS_HERE):
https://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001?addr=IP_ADDRESS_HERE&format=json
