### ISSUE TITLE
Server isn't queryable

### ISSUE THREAD

**Issue by Takanashi-Rikka1** [Hembi/cs16-pterodactyl-egg#11]
Hello!
first of all thank you so much for such a great egg, easy and works great.
i noticed to one problem, servers don't response to query requests..
so tracking tools like websites / bots / plugins which track servers information don't work with that.
the solution is installing ReHLDS, but sometimes not everyone (include me) need it or want to use that addon.
then may you please check if there's anything you could do to fix that?
after all with clean HLDS installation via your egg, query responses don't work.
Thanks in advance!

**Comment by Hembi** [comment]
Hello!

https://developer.valvesoftware.com/wiki/Half-Life_Dedicated_Server#Connectivity

Allow all these ports in your system firewall to accept the communication requests from bots and websites.
If you change the default server port also open it as UDP.

https://www.itweb.services/tutorials/linux-guides/how-to-install-counter-strike-1-6-server-on-linux/

**Comment by Takanashi-Rikka1** [comment]
> Hello!
> 
> https://developer.valvesoftware.com/wiki/Half-Life_Dedicated_Server#Connectivity
> 
> Allow all these ports in your system firewall to accept the communication requests from bots and websites. If you change the default server port also open it as UDP.
> 
> https://www.itweb.services/tutorials/linux-guides/how-to-install-counter-strike-1-6-server-on-linux/

I'm not sure if it's resolution, i decided to bring up the problem because i checked another egg and there it worked
with no action needed by my side..
so i wondered if there's anything you could do in your egg to make it work.
anyway it's not a big deal or game changer, 
thank you for your response & support Hembi!
